# Generated by Django 4.1.3 on 2022-11-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0005_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="djangodbmodelsfieldscharfield", max_length=200, unique=True
            ),
        ),
    ]
