# Generated by Django 4.1.3 on 2022-11-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0007_alter_post_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subsribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
