# Generated by Django 4.1.3 on 2022-11-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0008_subsribe"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
